---
- name: update packages
  apt:
    update_cache: yes

- name: disable swap
  shell: swapoff -a

- name: remove swap entry from /etc/fstab
  lineinfile:
    dest: /etc/fstab
    regexp: swap
    state: absent

- name: enable IPv4 packet forwarding
  shell: |
    cat <<EOF | tee /etc/sysctl.d/k8s.conf
    net.ipv4.ip_forward = 1
    EOF

- name: apply sysctl params without reboot
  shell: sysctl --system
